apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: test-app
  newName: 899864473854.dkr.ecr.ap-northeast-2.amazonaws.com/ci-test/test-app
  newTag: 0.1.2
resources:
- ../base
